// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALahqvWgaQdEcbP4lcaCgArdOmSPMIl_M',
    appId: '1:1087668556516:web:24d155da6e4498178b12f1',
    messagingSenderId: '1087668556516',
    projectId: 'flutter-final-app-10398',
    authDomain: 'flutter-final-app-10398.firebaseapp.com',
    storageBucket: 'flutter-final-app-10398.firebasestorage.app',
    measurementId: 'G-3LS1LETRGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAJnAalEEXsVOOCFu9Vtl6i4QRouNAFwY',
    appId: '1:1087668556516:android:4c5a9a0add600e3a8b12f1',
    messagingSenderId: '1087668556516',
    projectId: 'flutter-final-app-10398',
    storageBucket: 'flutter-final-app-10398.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeHx57DfIhu6MQamMZy_hArfIIMxtH9I8',
    appId: '1:1087668556516:ios:1e5b7a7a517f34ac8b12f1',
    messagingSenderId: '1087668556516',
    projectId: 'flutter-final-app-10398',
    storageBucket: 'flutter-final-app-10398.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeHx57DfIhu6MQamMZy_hArfIIMxtH9I8',
    appId: '1:1087668556516:ios:1e5b7a7a517f34ac8b12f1',
    messagingSenderId: '1087668556516',
    projectId: 'flutter-final-app-10398',
    storageBucket: 'flutter-final-app-10398.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALahqvWgaQdEcbP4lcaCgArdOmSPMIl_M',
    appId: '1:1087668556516:web:b9d9d01360e990358b12f1',
    messagingSenderId: '1087668556516',
    projectId: 'flutter-final-app-10398',
    authDomain: 'flutter-final-app-10398.firebaseapp.com',
    storageBucket: 'flutter-final-app-10398.firebasestorage.app',
    measurementId: 'G-DP2866QRBZ',
  );
}
